QWEN_MODEL_ID = "Qwen/Qwen3-0.6B"
SMOL_MODEL_ID = "HuggingFaceTB/SmolLM2-135M-Instruct"
# AMBER_DATASET_PATH = "./data/amber"
AMBER_DATASET_PATH = "./data/amber_small_1000"
EPSILON = 1e-6
BATCH_SIZE = 4
MAX_SEQUENCE_LENGTH = 1024
